RPPatients/Controllers/RPMedicationTypeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RPPatients.Models;

namespace RPPatients.Controllers
{
    public class RPMedicationTypeController : Controller
    {
        private readonly PatientsContext _context;

        public RPMedicationTypeController(PatientsContext context)
        {
            _context = context;
        }

        // GET: RPMedicationType
        // Action to view contents from MedicationType table
        public async Task<IActionResult> Index()
        {
            return View(await _context.MedicationTypes.OrderBy(m => m.Name).ToListAsync());
        }

        // GET: RPMedicationType/Details/5
        //Action used to get details from MedicationType table
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.MedicationTypes == null)
            {
                return NotFound();
            }

            var medicationType = await _context.MedicationTypes
                .FirstOrDefaultAsync(m => m.MedicationTypeId == id);
            if (medicationType == null)
            {
                return NotFound();
            }

            return View(medicationType);
        }

        // GET: RPMedicationType/Create
        //Action used to create setup,to display a blank input page 
        public IActionResult Create()
        {
            return View();
        }

        // POST: RPMedicationType/Create
        //Action to create data and check if the data is valid
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("MedicationTypeId,Name")] MedicationType medicationType)
        {
            if (ModelState.IsValid)
            {
                _context.Add(medicationType);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(medicationType);
        }

        // GET: RPMedicationType/Edit/5
        //Action used to update data
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.MedicationTypes == null)
            {
                return NotFound();
            }

            var medicationType = await _context.MedicationTypes.FindAsync(id);
            if (medicationType == null)
            {
                return NotFound();
            }
            return View(medicationType);
        }

        // POST: RPMedicationType/Edit/5
        //Action used to send data to be edited
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("MedicationTypeId,Name")] MedicationType medicationType)
        {
            if (id != medicationType.MedicationTypeId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(medicationType);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MedicationTypeExists(medicationType.MedicationTypeId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(medicationType);
        }

        // GET: RPMedicationType/Delete/5
        //Action used ensure data to be deleted
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.MedicationTypes == null)
            {
                return NotFound();
            }

            var medicationType = await _context.MedicationTypes
                .FirstOrDefaultAsync(m => m.MedicationTypeId == id);
            if (medicationType == null)
            {
                return NotFound();
            }

            return View(medicationType);
        }

        // POST: RPMedicationType/Delete/5
        //Action used ensure data to be deleted
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.MedicationTypes == null)
            {
                return Problem("Entity set 'PatientsContext.MedicationTypes'  is null.");
            }
            var medicationType = await _context.MedicationTypes.FindAsync(id);
            if (medicationType != null)
            {
                _context.MedicationTypes.Remove(medicationType);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MedicationTypeExists(int id)
        {
          return _context.MedicationTypes.Any(e => e.MedicationTypeId == id);
        }
    }
}

RPPatients/Controllers/RPMedicationsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RPPatients.Models;

namespace RPPatients.Controllers
{
    public class RPMedicationsController : Controller
    {
        private readonly PatientsContext _context;

        public RPMedicationsController(PatientsContext context)
        {
            _context = context;
        }

        // GET: RPMedications
        public async Task<IActionResult> Index(string MedicationTypeID)
        {
            //Storing the Query value into Cookie
            //Retriving the value when necessry
            if (MedicationTypeID != null)
            {
                Response.Cookies.Append("MedicationTypeID", MedicationTypeID);
            }
            else if (Request.Query["MedicationTypeID"].Any())
            {
                Request.Query["MedicationTypeID"].ToString();
                Response.Cookies.Append("MedicationTypeID", MedicationTypeID);
            }
            else if (Request.Cookies["MedicationTypeID"] != null)
            {
                MedicationTypeID = Request.Cookies["MedicationTypeID"].ToString();
            }
            else
            {
                TempData["message"] = "Please select any Medication Type ID";
                return RedirectToAction("Index", "RPSMedicationTypes");
            }

            //Naming the title
            var medType = _context.MedicationTypes.Where(a => a.MedicationTypeId == Convert.ToInt16(MedicationTypeID)).FirstOrDefault();
            ViewData["MTName"] = medType.Name;

            //Ordring and Showing the value according to the Medication Type ID
            var patientsContext = _context.Medications
                .Include(m => m.ConcentrationCodeNavigation)
                .Include(m => m.DispensingCodeNavigation)
                .Include(m => m.MedicationType)
                .Where(m => m.MedicationTypeId == Convert.ToInt16(MedicationTypeID))
                .OrderBy(m => m.Name).ThenBy(m => m.Concentration);
            return View(await patientsContext.ToListAsync());
        }
        //Action used to view details
        // GET: RPMedications/Details/5
        public async Task<IActionResult> Details(string id)
        {
            //Retriving the value from the cookies
            string medTypeID = string.Empty;
            if (Request.Cookies["MedicationTypeID"] != null)
            {
                medTypeID = Request.Cookies["MedicationTypeID"].ToString();
            }

            //Naming the title
            var medType = _context.MedicationTypes.Where(a => a.MedicationTypeId == Convert.ToInt32(medTypeID)).FirstOrDefault();
            ViewData["MTName"] = medType.Name;

            if (id == null || _context.Medications == null)
            {
                return NotFound();
            }

            var medication = await _context.Medications
                .Include(m => m.ConcentrationCodeNavigation)
                .Include(m => m.DispensingCodeNavigation)
                .Include(m => m.MedicationType)
                .FirstOrDefaultAsync(m => m.Din == id);
            if (medication == null)
            {
                return NotFound();
            }

            return View(medication);
        }
        //Action used to create data
        // GET: RPMedications/Create
        public IActionResult Create()
        {
            //Retriving the value from the cookies
            int medTypeID = 0;
            if (Request.Cookies["MedicationTypeID"] != null)
            {
                medTypeID = Convert.ToInt32(Request.Cookies["MedicationTypeID"]);
            }

            //Naming the title
            var medType = _context.MedicationTypes.Where(a => a.MedicationTypeId == Convert.ToInt32(medTypeID)).FirstOrDefault();
            ViewData["MTName"] = medType.Name;
            //Console.Write(medType);
            //int bool = await DisplayAlert("Alert", "You have been alerted", "OK");
            ViewData["ConcentrationCode"] = new SelectList(_context.ConcentrationUnits.OrderBy(a => a.ConcentrationCode), "ConcentrationCode", "ConcentrationCode");
            ViewData["DispensingCode"] = new SelectList(_context.DispensingUnits.OrderBy(a => a.DispensingCode), "DispensingCode", "DispensingCode");
            ViewData["MedicationTypeId"] = new SelectList(_context.MedicationTypes, "MedicationTypeId", "MedicationTypeId", medTypeID);
            return View();
        }

        // POST: RPMedications/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        //Action used to create data in database
        public async Task<IActionResult> Create([Bind("Din,Name,Image,MedicationTypeId,DispensingCode,Concentration,ConcentrationCode")] Medication medication)
        {
            //Retriving the value from the cookies
            int medTypeID = 0;
            if (Request.Cookies["MedicationTypeID"] != null)
            {
                medTypeID = Convert.ToInt32(Request.Cookies["MedicationTypeID"]);
            }

            //Naming the title
            var medType = _context.MedicationTypes.Where(a => a.MedicationTypeId == Convert.ToInt32(medTypeID)).FirstOrDefault();
            ViewData["MTName"] = medType.Name;

            //Checking if it is duplicate value then show error
            var isDuplicate = _context.Medications.Where(a => a.Name == medication.Name && a.Concentration == medication.Concentration && a.ConcentrationCode == a.ConcentrationCode);
            if (isDuplicate.Any())
            {
                ModelState.AddModelError("", "Already exists in the database");
            }

            if (ModelState.IsValid)
            {
                _context.Add(medication);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            //Showing the value in accending order
            ViewData["ConcentrationCode"] = new SelectList(_context.ConcentrationUnits.OrderBy(a => a.ConcentrationCode), "ConcentrationCode", "ConcentrationCode", medication.ConcentrationCode);
            ViewData["DispensingCode"] = new SelectList(_context.DispensingUnits.OrderBy(a => a.DispensingCode), "DispensingCode", "DispensingCode", medication.DispensingCode);
            ViewData["MedicationTypeId"] = new SelectList(_context.MedicationTypes, "MedicationTypeId", "MedicationTypeId", medTypeID);
            return View(medication);
        }
        //Action used to send data to be edit page
        // GET: RPMedications/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            //Retriving the value from the cookies
            string medTypeID = string.Empty;
            if (Request.Cookies["MedicationTypeID"] != null)
            {
                medTypeID = Request.Cookies["MedicationTypeID"].ToString();
            }

            //Naming the title
            var medType = _context.MedicationTypes.Where(a => a.MedicationTypeId == Convert.ToInt32(medTypeID)).FirstOrDefault();
            ViewData["MTName"] = medType.Name;

            if (id == null || _context.Medications == null)
            {
                return NotFound();
            }

            var medication = await _context.Medications.FindAsync(id);
            if (medication == null)
            {
                return NotFound();
            }

            //Showing the value in accending order
            ViewData["ConcentrationCode"] = new SelectList(_context.ConcentrationUnits.OrderBy(a => a.ConcentrationCode), "ConcentrationCode", "ConcentrationCode", medication.ConcentrationCode);
            ViewData["DispensingCode"] = new SelectList(_context.DispensingUnits.OrderBy(a => a.DispensingCode), "DispensingCode", "DispensingCode", medication.DispensingCode);
            ViewData["MedicationTypeId"] = new SelectList(_context.MedicationTypes, "MedicationTypeId", "MedicationTypeId", medication.MedicationTypeId);
            return View(medication);
        }
        //Action used to edit data in database
        // POST: RPMedications/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("Din,Name,Image,MedicationTypeId,DispensingCode,Concentration,ConcentrationCode")] Medication medication)
        {
            //Retriving the value from the cookies
            string medTypeID = string.Empty;
            if (Request.Cookies["MedicationTypeID"] != null)
            {
                medTypeID = Request.Cookies["MedicationTypeID"].ToString();
            }

            //Naming the title
            var medType = _context.MedicationTypes.Where(a => a.MedicationTypeId == Convert.ToInt32(medTypeID)).FirstOrDefault();
            ViewData["MTName"] = medType.Name;

            if (id != medication.Din)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(medication);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MedicationExists(medication.Din))
                    {
                        return NotFound();
                    }

RPPatients/Views/RPMedicationType/Create.cshtml
@model RPPatients.Models.MedicationType

@{
    ViewData["Title"] = "Create Medication Type";
}

<h1>Create</h1>

<h4>MedicationType</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

RPPatients/Views/RPMedicationType/Delete.cshtml
@model RPPatients.Models.MedicationType

@{
    ViewData["Title"] = "Delete Medication Type";
}

<h1>Delete Medication Type</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>MedicationType</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.MedicationTypeId)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.MedicationTypeId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="MedicationTypeId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

RPPatients/Views/RPMedicationType/Details.cshtml
@model RPPatients.Models.MedicationType

@{
    ViewData["Title"] = "Medication Type Details";
}

<h1>Medication Type Details</h1>

<div>
    <h4>MedicationType</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.MedicationTypeId)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.MedicationTypeId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.MedicationTypeId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

RPPatients/Views/RPMedicationType/Edit.cshtml
@model RPPatients.Models.MedicationType

@{
    ViewData["Title"] = "Edit Medication Type";
}

<h1>Edit Medication Type</h1>

<h4>MedicationType</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="MedicationTypeId" class="control-label"></label>
                <input asp-for="MedicationTypeId" type="text" disabled class="form-control" />
                <span asp-validation-for="MedicationTypeId" class="text-danger" readonly></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

RPPatients/Views/RPMedicationType/Index.cshtml
@model IEnumerable<RPPatients.Models.MedicationType>

@{
    ViewData["Title"] = "Medication Type Details";
}

<h1>Medication Type Details</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.MedicationTypeId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.MedicationTypeId)
            </td>
            <td>
                    <a asp-action="Index" asp-controller="RPMedications" asp-route-MedicationTypeID="@item.MedicationTypeId">@Html.DisplayFor(modelItem => item.Name)</a>
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.MedicationTypeId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.MedicationTypeId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.MedicationTypeId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>